
package servidor;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-11-09T16:17:07.646-03:00
 * Generated source version: 4.0.5
 */

@WebFault(name = "ClaseRepetidoException", targetNamespace = "http://servidor/")
public class ClaseRepetidoException_Exception extends Exception {

    private servidor.ClaseRepetidoException faultInfo;

    public ClaseRepetidoException_Exception() {
        super();
    }

    public ClaseRepetidoException_Exception(String message) {
        super(message);
    }

    public ClaseRepetidoException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public ClaseRepetidoException_Exception(String message, servidor.ClaseRepetidoException claseRepetidoException) {
        super(message);
        this.faultInfo = claseRepetidoException;
    }

    public ClaseRepetidoException_Exception(String message, servidor.ClaseRepetidoException claseRepetidoException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = claseRepetidoException;
    }

    public servidor.ClaseRepetidoException getFaultInfo() {
        return this.faultInfo;
    }
}
