
package servidor;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-11-09T16:17:07.653-03:00
 * Generated source version: 4.0.5
 */

@WebFault(name = "ClaseNoExisteException", targetNamespace = "http://servidor/")
public class ClaseNoExisteException_Exception extends Exception {

    private servidor.ClaseNoExisteException faultInfo;

    public ClaseNoExisteException_Exception() {
        super();
    }

    public ClaseNoExisteException_Exception(String message) {
        super(message);
    }

    public ClaseNoExisteException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public ClaseNoExisteException_Exception(String message, servidor.ClaseNoExisteException claseNoExisteException) {
        super(message);
        this.faultInfo = claseNoExisteException;
    }

    public ClaseNoExisteException_Exception(String message, servidor.ClaseNoExisteException claseNoExisteException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = claseNoExisteException;
    }

    public servidor.ClaseNoExisteException getFaultInfo() {
        return this.faultInfo;
    }
}
